### ISSUE TITLE
Cannot find node/path.ts polyfill

### ISSUE THREAD

**Issue by cdoremus** [quaos/deno-react-minimal-frontend#3]
I made a simple change to the HTML in App.tsx, ran `npm run build` and got the following error:
```
craig@craig-G750JX:~/git/deno/deno-react-minimal-frontend$ deno run --allow-env --allow-net --allow-read --allow-write --unstable https://deno.land/x/denopack@0.8.0/cli.ts -c denopack.config.ts
Warning Failed to get compiled source code of "https://cdn.dreg.dev/polyfill/node/path.ts".
Reason: No such file or directory (os error 2)
```
This same error was found on my Macbook Pro and Ubuntu machines.

**Comment by quaos** [comment]
@cdoremus I can't reproduce it on my machine.
Which deno version are you using?

```shell
$ npm run build

> deno-react-minimal-frontend@1.0.1 build /Users/chakrit_w/Projects/deno-react-minimal-frontend
> deno run --allow-env --allow-net --allow-read --allow-write --unstable https://deno.land/x/denopack@0.8.0/cli.ts -c denopack.config.ts

denopack completed in 7953ms
```

**Comment by cdoremus** [comment]
I am using 1.3.2 on both machines. 

It worked fine until I tried to make a very small HTML change to the JSX and then the build did not work.

The same error occurred if I ran `npm run build` or the `deno run` command that is shown above.

**Comment by cdoremus** [comment]
I was able to get this to work after I installed `denopack`. 

You need to add this requirement to the Readme. When that is done, you can close this issue. Thank you.

**Comment by quaos** [comment]
@cdoremus I see. Even if using call to denopack cli.ts remotely, we still need to install their components locally first. Will update this accordingly.
